apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: frontend-dev
          image: asia-southeast2-docker.pkg.dev/am-finalproject/frontend-repo/web:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dev
spec:
  selector:
    app: frontend-dev
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
  type: ClusterIP 

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-dev
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`web.42n.fun`)
      kind: Rule
      services:
        - name: frontend-dev
          port: 8080