apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: default
spec:
  headers:
    # Menggabungkan semua header keamanan dalam satu tempat
    customResponseHeaders:
      X-Content-Type-Options: nosniff
      Content-Security-Policy: >-
        frame-ancestors 'none';
        default-src 'self' https://backend.42n.fun;
        script-src 'self' https://www.gstatic.com https://cdn.firebase.com https://www.google.com;
        connect-src 'self' https://backend.42n.fun https://www.googleapis.com https://securetoken.googleapis.com https://www.google.com https://identitytoolkit.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com;
        img-src 'self' data: https://www.gstatic.com https://www.google.com;
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.gstatic.com;
        font-src 'self' data: https://fonts.gstatic.com;
        frame-src 'self' https://www.google.com;
        form-action 'self';
      # X-Frame-Options juga bisa ditambahkan di sini, tapi CSP frame-ancestors sudah mencakupnya
      X-Frame-Options: DENY