apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: asia-southeast2-docker.pkg.dev/am-finalproject/fathya-frontend-repo/fe-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`frontend.42n.fun`)
      kind: Rule
      services:
        - name: frontend-app
          port: 8080
      middlewares:
        - name: security-headers